# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-02 12:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import edc_base.model.validators.date


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=25)),
                ('model_name', models.CharField(max_length=25)),
                ('start_datetime', models.DateTimeField(validators=[edc_base.model.validators.date.datetime_not_before_study_start], verbose_name='Valid starting')),
                ('end_datetime', models.DateTimeField(validators=[edc_base.model.validators.date.datetime_not_before_study_start], verbose_name='Valid ending')),
                ('version', models.CharField(max_length=10)),
                ('updates_version', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'ordering': ['app_label', 'model_name', 'version', 'updates_version'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalConsentType',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('app_label', models.CharField(max_length=25)),
                ('model_name', models.CharField(max_length=25)),
                ('start_datetime', models.DateTimeField(validators=[edc_base.model.validators.date.datetime_not_before_study_start], verbose_name='Valid starting')),
                ('end_datetime', models.DateTimeField(validators=[edc_base.model.validators.date.datetime_not_before_study_start], verbose_name='Valid ending')),
                ('version', models.CharField(max_length=10)),
                ('updates_version', models.CharField(blank=True, max_length=50, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'get_latest_by': 'history_date',
                'verbose_name': 'historical consent type',
                'ordering': ('-history_date', '-history_id'),
            },
        ),
        migrations.AlterUniqueTogether(
            name='consenttype',
            unique_together=set([('app_label', 'model_name', 'version')]),
        ),
    ]
