# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-25 17:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edc_consent', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalconsenttype',
            name='history_user',
        ),
        migrations.DeleteModel(
            name='HistoricalConsentType',
        ),
    ]
