from .identity_fields_mixin import IdentityFieldsMixin
from .personal_fields_mixin import PersonalFieldsMixin
from .review_fields_mixin import ReviewFieldsMixin
from .sample_collection_fields_mixin import SampleCollectionFieldsMixin
from .scored_review_fields_mixin import ScoredReviewFieldsMixin
from .site_fields_mixin import SiteFieldsMixin
from .vulnerability_fields_mixin import VulnerabilityFieldsMixin
